### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by alfonsotech** [andybeers/portfolio#9]
<img width="937" alt="screen shot 2016-09-23 at 10 25 02 pm" src="https://cloud.githubusercontent.com/assets/15456287/18806278/c51c0212-81dc-11e6-8200-23422a1581a3.png">

Attached is a pic of your website with numbered areas circled in red. These are things to try that may improve the feel and look of your site (and the User Experience):
1.Give your ,main-header some more breathing room by adding some padding or margin below and on top. Right now, you are allowing the content to set it's height.
2. Add a space between the social media icon and its name.
3. The space between your project holders is uneven, and the top/bottom contact looks especially tight. I'd consider adding some space (margin or padding) in between projects here.
4. Are those hashtags (#) supposed to be showing up? I know these are placeholders but it could be better to leave them out until you have the content ready.
5. Leaving the background white is sometimes interpreted as your site breaking. Consider using a slightly off white, or a light color to get away from the pure, bright, white.

Overall good work on putting it together - it looks well organized and logical. :-)

**Comment by andybeers** [comment]
Great input on all of these, thank you! 

1) Added padding to the header h1 and h2 elements
2) Properly spaced out the media icons from the span text in the nav li
3) Made these margins a little bit more even, but I have no idea how to make them uniform! Since the left/right is determined by a % in a flex container, but the top/bottom is em units, I'm really having trouble figuring out how to keep a responsive, uniform grid. I'll keep working on this!
4) Yes, just placeholders, but I replaced them with "Placeholder title" to look a little more clean
5) Noted. Trying out a light gray instead
